name: Create an issue
description: Creates a new issue using a template with front matter.
runs:
  using: node12
  main: index.js
branding:
  icon: alert-circle
  color: gray-dark
inputs:
  json:
    descrption: path to json file containing issues and milestones
    required: true
