name: Create a list of issues
on:
  workflow_call:
    inputs:
      json:
        required: true
        type: string
permissions:
  contents: read
  issues: write
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./create-issues
        with:
          json: ${{ inputs.json }}
